### ISSUE TITLE
save total elastic cross section to hdf5

### ISSUE THREAD

**Issue by atheulings** [eScatter/cstool#6]
Only the cumulative density function per energy per angle is saved to hdf5. The total elastic cross section per energy should also be saved.

**Comment by atheulings** [comment]
Is there already a function that could do this? Otherwise I will write a function for this and you can assign this issue to me.

**Comment by slokhorst** [comment]
I think there's already some work in the [*hdf5* branch](https://github.com/eScatter/cstool/tree/hdf5) (check out the last commit).

**Comment by lvkessel** [comment]
HDF5 branch fixes this issue and was merged into master today.
